stages:
  - test

test:pytest:
  image: python:${VERSION}
  parallel:
    matrix:
      - VERSION: [ "3.8", "3.9", "3.10", "latest" ]
  stage: test
  before_script:
    - apt-get update && apt-get install libgl1  -y
    - pip install --upgrade pip
    - pip install numpy # actually installed via pyproject.toml but pyradiomics requires it already during installation
    - pip install pytest
  script:
    - pip install .
    - pytest tests/
  #artifacts:
  #  paths:
  #    - results/
