stages:
  - test
  - run

test:pytest:
  image: python:3.10
  stage: test
  before_script:
    - pip install --upgrade pip
    - pip install numpy
    - pip install pytest
  script:
    - pytest $CI_PROJECT_DIR/test/

test:run:
  image: python:3.10
  stage: run
  before_script:
    - pip install --upgrade pip
    - pip install numpy
  script:
    - python setup.py install
    - radtract_features -h
    - radtract_parcellate -h
