stages:
  - test

test:pytest:
  image: python:3.10
  stage: test
  before_script:
    - apt-get update && apt-get install libgl1  -y
    - pip install --upgrade pip
    - pip install numpy # actually installed via pyproject.toml but pyradiomics requires it already during installation
    - pip install pytest
  script:
    - pip install .
    - pytest tests/
  rules:
    if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - results/
