stages:
  - install
  - test

test:install:
  image: python:3.10
  stage: install
  before_script:
    - pip install --upgrade pip
    - pip install numpy
  script:
    - python setup.py install

test:pytest:
  image: python:3.10
  stage: test
  before_script:
    - pip install --upgrade pip
    - pip install numpy
    - pip install pytest
  script:
    - pytest test/