# Copyright © 2023 German Cancer Research Center (DKFZ), Division of Medical Image Computing
#
# SPDX-License-Identifier: Apache-2.0

stages:
  - lint
  - test 

license_compliance:
  image: python:3.10
  stage: lint
  before_script:
    - pip install --upgrade pip
    - pip install reuse
  script:
    - reuse lint
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.default_before_script: &default_before_script
  - apt-get update && apt-get install libgl1  -y
  - pip install --upgrade pip
  - pip install numpy # actually installed via pyproject.toml but pyradiomics requires it already during installation
  - pip install pytest

test_pytest:
  image: python:${VERSION}
  parallel:
    matrix:
      - VERSION: [ "3.8", "3.9", "3.10", "latest" ]
  stage: test
  before_script:
    - *default_before_script
  script:
    - pip install .
    - pytest tests/
  artifacts:
    paths:
      - test/test_results/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test_run_parcellate:
  extends: test_pytest
  before_script:
    - *default_before_script
    - pip install .
    - mkdir test/test_results/ -p
  script:
    - radtract_parcellate --streamlines tests/test_data/test_tract.trk --envelope tests/test_data/test_tract_envelope.nii.gz --start tests/test_data/test_tract_b.nii.gz --num_parcels 5 --output test/test_results/hyperplane_parcellation_command.nii.gz

test_run_features:
  extends: test_run_parcellate
  script:
    - radtract_features --parcellation test/test_results/hyperplane_parcellation_command.nii.gz --map tests/test_data/test_map.nii.gz --output test/test_results/hyperplane_parcellation_command.csv
  dependencies:
    - test_run_parcellate
