stages:
  - test
  - run

test:pytest:
  image: python:3.10
  stage: test
  before_script:
    - pip install --upgrade pip
    - python -m venv testenv
    - source testenv/bin/activate
    - pip install -r requirements.txt
  script:
    - pytest tests/

test:run:
  image: python:3.10
  stage: run
  before_script:
    - pip install --upgrade pip
    - python -m venv testenv
    - source testenv/bin/activate
  script:
    - python setup.py install
    - radtract_features -h
    - radtract_parcellate -h
