stages:
  - test

test:pytest:
  image: python:3.10
  stage: test
  before_script:
    - python -m venv testenv
    - source testenv/bin/activate
    - pip install --upgrade pip
    - pip install numpy
    - pip install -r requirements.txt
  script:
    - python setup.py install
    - pytest tests/
    - radtract_features -h
    - radtract_parcellate -h

